package Hospital_Management_System.View;

import Hospital_Management_System.Controller.Ward;
import Hospital_Management_System.Model.Ward_creation_Model;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author GAYANI
 */
public class Enter_Ward_Details_View extends javax.swing.JFrame {

    private String name;
    
    public Enter_Ward_Details_View() {
        initComponents();
        Utility_Class_View.Date(date_label);
        Utility_Class_View.Time(time_label);
        Ward_creation_Model ac = new Ward_creation_Model(ward_table_view, ward_id_label);
        ac.ward_table();
        ac.autoAID();
    }
     public Enter_Ward_Details_View(String n) {
        name = n; 
        initComponents();
        Utility_Class_View.Date(date_label);
        Utility_Class_View.Time(time_label);
        Ward_creation_Model ac = new Ward_creation_Model(ward_table_view, ward_id_label);
        ac.ward_table();
        ac.autoAID();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        wardtypebox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        dnamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noofnursesbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        noofbedsbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        noofpatientsbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ward_id_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ward_table_view = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ward Creation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("WardType: ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        wardtypebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Medical Ward", "Surgical Ward", "Cardiology Ward" }));
        jPanel3.add(wardtypebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Doctor Name: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        jPanel3.add(dnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("No of Nurses: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        noofnursesbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofnursesboxActionPerformed(evt);
            }
        });
        jPanel3.add(noofnursesbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("No of Beds: ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        jPanel3.add(noofbedsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("No of Patients:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 20));

        noofpatientsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofpatientsboxActionPerformed(evt);
            }
        });
        jPanel3.add(noofpatientsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Ward no: ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));
        jPanel3.add(ward_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 430, 360));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Back");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(updatebtn))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbtn)
                    .addComponent(deletebtn))
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 340, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 680));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ward_table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ward No", "Ward Type", "Doctor Name", "No of Nurses", "No of Beds", "No of Patient"
            }
        ));
        ward_table_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ward_table_viewMouseClicked(evt);
            }
        });
        ward_table_view.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ward_table_viewKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ward_table_view);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 580, 570));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Time:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 80, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Date:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, 30));
        jPanel2.add(time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 70, 30));
        jPanel2.add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 680, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noofnursesboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofnursesboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofnursesboxActionPerformed

    private void noofpatientsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofpatientsboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noofpatientsboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Ward ad1;
        ad1 = new Ward(wardtypebox, dnamebox, noofnursesbox, noofbedsbox, noofpatientsbox, ward_id_label);
        ad1.insertToTable(ward_table_view, ward_id_label);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ward_table_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ward_table_viewMouseClicked
        Ward ad3;
        ad3 = new Ward(wardtypebox, dnamebox, noofnursesbox, noofbedsbox, noofpatientsbox, ward_id_label);
        ad3.getSelectedValues(jButton3, ward_table_view);
        
    }//GEN-LAST:event_ward_table_viewMouseClicked

    private void ward_table_viewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ward_table_viewKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ward_table_viewKeyReleased

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
           Ward ad2;
        ad2 = new Ward(wardtypebox, dnamebox, noofnursesbox, noofbedsbox, noofpatientsbox, ward_id_label);
        ad2.updateTable(ward_table_view, ward_id_label, jButton3); 
     
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        Ward ad4;
        ad4 = new Ward(wardtypebox, dnamebox, noofnursesbox, noofbedsbox, noofpatientsbox, ward_id_label);
        ad4.deleteItem(ward_table_view, ward_id_label, jButton3);
        
       
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Administrative_S_M_View ob = new Administrative_S_M_View(name);
        ob.setVisible(true);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter_Ward_Details_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter_Ward_Details_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter_Ward_Details_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter_Ward_Details_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enter_Ward_Details_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_label;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField dnamebox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noofbedsbox;
    private javax.swing.JTextField noofnursesbox;
    private javax.swing.JTextField noofpatientsbox;
    private javax.swing.JLabel time_label;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel ward_id_label;
    private javax.swing.JTable ward_table_view;
    private javax.swing.JComboBox wardtypebox;
    // End of variables declaration//GEN-END:variables
}
