/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_Management_System.View;

import Hospital_Management_System.Controller.OPD_Patient;
import Hospital_Management_System.Controller.Staying_Patient;
import Hospital_Management_System.Model.Patient_Creation_Model;
import javax.swing.JOptionPane;





/**
 *
 * @author Thisura
 */
public class Patient_Creation_View extends javax.swing.JFrame {
    private String name;
    /**
     * Creates new form Administrator_Creation_Interface
     */
    public Patient_Creation_View() {
       initComponents();
       Patient_Creation_Model ac = new Patient_Creation_Model(PatientTable_view, patient_id_label);
       ac.patient_table();
       ac.autoAID();
  
    }
    
     public Patient_Creation_View(String n) {
         name = n;
       initComponents();
       Patient_Creation_Model ac = new Patient_Creation_Model(PatientTable_view, patient_id_label);
       ac.patient_table();
       ac.autoAID();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientTable_view = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        fName_tBox = new javax.swing.JTextField();
        NICNo_tBox = new javax.swing.JTextField();
        lName_tBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        patient_id_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        age_tbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        conNumber_tbox = new javax.swing.JTextField();
        genderSelection = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        patientTypeSelection = new javax.swing.JComboBox();
        ward_number_tbox = new javax.swing.JTextField();
        wardSelection = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        searchbox1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientTable_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Age", "Gender", "NIC Number", "Contract Number", "Patient Type", "Ward Number"
            }
        ));
        PatientTable_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientTable_viewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PatientTable_view);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 931, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 146, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 146, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC Number:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 191, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 191, -1, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 300, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 300, -1, -1));

        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 300, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 300, -1, -1));

        fName_tBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fName_tBoxActionPerformed(evt);
            }
        });
        jPanel1.add(fName_tBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 137, -1));
        jPanel1.add(NICNo_tBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 188, 144, -1));
        jPanel1.add(lName_tBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 143, 144, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Patient Creation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, 20));

        patient_id_label.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.add(patient_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 99, 24));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 146, -1, -1));

        age_tbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_tboxActionPerformed(evt);
            }
        });
        jPanel1.add(age_tbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 137, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contract Number: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 191, -1, -1));
        jPanel1.add(conNumber_tbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 139, -1));

        genderSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Felame", " " }));
        jPanel1.add(genderSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 137, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patient Type:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 237, -1, -1));

        patientTypeSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OPD Patient", "Staying Patient" }));
        jPanel1.add(patientTypeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 137, -1));
        jPanel1.add(ward_number_tbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 314, 52, -1));

        wardSelection.setText(" Ward Number:");
        wardSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardSelectionActionPerformed(evt);
            }
        });
        jPanel1.add(wardSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 313, 118, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Doctor Name Here", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        searchbox1.setToolTipText("Patient name");
        searchbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbox1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 34, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Medicine-drugs-colorful-dollars_2880x1800.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fName_tBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fName_tBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fName_tBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO pass var of feilds
        //fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, wardSelection, ward_number_tbox, patientTypeSelection
        // patient_id_label
        
        String patientType = patientTypeSelection.getSelectedItem().toString();
      
        
        if (patientType == "OPD Patient"){
            if(wardSelection.isSelected()){
                JOptionPane.showMessageDialog(this, "OPD patient can't have a Ward! ");
            }
            else{
                OPD_Patient op1;
                op1 = new OPD_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, patientTypeSelection, patient_id_label);
                op1.insertToTable(PatientTable_view,patient_id_label);
                
            }
            
        }
        else if (patientType == "Staying Patient"){
            if(wardSelection.isSelected()){
                Staying_Patient st1;
                st1 = new Staying_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, ward_number_tbox, patientTypeSelection, patient_id_label);
                st1.insertToTable(PatientTable_view,patient_id_label);
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select Ward and give the Ward Number! ");

            }
            
        }
       
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        
        Receptionist_View mI;
        mI = new Receptionist_View(name);
        mI.setVisible(true);
      
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String patientType = patientTypeSelection.getSelectedItem().toString();
      
        
        if (patientType == "OPD Patient"){
            if(wardSelection.isSelected()){
                JOptionPane.showMessageDialog(this, "OPD patient can't have a Ward! ");
            }
            else{
                OPD_Patient op1;
                op1 = new OPD_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, patientTypeSelection, patient_id_label);
                op1.updateTable( PatientTable_view, patient_id_label, jButton3);
                
            }
            
        }
        else if (patientType == "Staying Patient"){
            if(wardSelection.isSelected()){
                Staying_Patient st1;
                st1 = new Staying_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, ward_number_tbox, patientTypeSelection, patient_id_label);
                st1.updateTable( PatientTable_view, patient_id_label, jButton3);
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select Ward and give the Ward Number! ");

            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PatientTable_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientTable_viewMouseClicked
        // TODO add your handling code here:///////////////////////////////////////////////
                Staying_Patient st1;
                st1 = new Staying_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, ward_number_tbox, patientTypeSelection, patient_id_label);
                st1.getSelectedValues(jButton3, patient_id_label, PatientTable_view);
        
        
    }//GEN-LAST:event_PatientTable_viewMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       Staying_Patient st2;
       st2 = new Staying_Patient(fName_tBox, lName_tBox, age_tbox, genderSelection, NICNo_tBox, conNumber_tbox, ward_number_tbox, patientTypeSelection, patient_id_label);
               
       st2.deleteItem(PatientTable_view, patient_id_label, jButton3);
        
        
     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wardSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardSelectionActionPerformed

    private void searchbox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbox1KeyReleased
        // TODO add your handling code here:
        Patient_Creation_Model ob = new Patient_Creation_Model();
        ob.search(searchbox1, PatientTable_view);
    }//GEN-LAST:event_searchbox1KeyReleased

    private void age_tboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_tboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_tboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Creation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Creation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Creation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Creation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Creation_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NICNo_tBox;
    private javax.swing.JTable PatientTable_view;
    private javax.swing.JTextField age_tbox;
    private javax.swing.JTextField conNumber_tbox;
    private javax.swing.JTextField fName_tBox;
    private javax.swing.JComboBox genderSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName_tBox;
    private javax.swing.JComboBox patientTypeSelection;
    private javax.swing.JLabel patient_id_label;
    private javax.swing.JTextField searchbox1;
    private javax.swing.JCheckBox wardSelection;
    private javax.swing.JTextField ward_number_tbox;
    // End of variables declaration//GEN-END:variables
}
